Add anchor CSS
QuiltMC/quilt-bulma pull request #12
Opened 2023-03-26 19:58 UTC by Akarys42

Add the CSS required for *PR link here in a minute*

2023-03-27 11:01 UTC, gdude2002 requested changes
Small PR, but not sure it matches the style conventions - not sure we have any selectors that long without splitting the line after the brace.

Also, please bump the version.

2023-03-28 00:25 UTC, pluiedev requested changes

2023-03-28 00:25 UTC, pluiedev commented on sass/components/anchors.scss
> +:where(h1, h2, h3, h4, h5, h6):hover a .header-anchor-container .header-anchor {
It's a bit too verbose for my liking — I'd write this instead:
```scss
:where(h1, h2, h3, h4, h5, h6) {
    a .header-anchor-container .header-anchor { 
        visibility: hidden;
    }
    &:hover a .header-anchor-container .header-anchor { 
        visibility: visible;
    }
}

2023-03-28 08:01 UTC, Akarys42 commented on sass/components/anchors.scss
> +:where(h1, h2, h3, h4, h5, h6):hover a .header-anchor-container .header-anchor {
This is very nitpicky

2023-03-28 12:29 UTC, gdude2002 commented
Everything's been addressed, so off we go.

2023-03-28 12:29 UTC, merged

2023-03-28 12:30 UTC, gdude2002 commented
Thanks!